### ISSUE TITLE
Bapcod issue

### ISSUE THREAD

**Issue by theSubsurfaceGuy** [inria-UFF/VRPSolverEasy#13]
Hello,

I understand that VRPSolverEasy  includes compiled libraries of BaPCod, its VRPSolver extension, and COIN-OR CLP solver, However I'm get the below error can you please take a look, thank you. 

raise ModelError(constants.LOAD_LIB_ERROR)
VRPSolverEasy.src.solver.ModelError: Cannot load or find library. Please ensure
               that the library bapcod are
               correctly installed on your system

**Comment by najibprog** [comment]
Hello, if you have this error after updating VRPSolverEasy, we removed binaries from the project in the new version, we invite you to read the documentation on this subject to know how to get the new binaries.

Best regards,
Najib

**Comment by theSubsurfaceGuy** [comment]
my question was answered, thanks najib, closing the issue now.
