### ISSUE TITLE
Support for M2 Mac

### ISSUE THREAD

**Issue by SmokeShine** [inria-UFF/VRPSolverEasy#16]
We downloaded the binary and kept in the corresponding folder. However, when using library, it is unable to find the binary. We put a trace and found that the cplex installed is arm64, while the library is looking for a binary compatible with x86_64. 
We repeated the same on M1 with x86_64, it works as intended. 
What remedial steps can we apply on M2 to make it work?

**Comment by rrsadykov** [comment]
Thank you for your interest in our solver. 
The library works only with x86_64 Cplex for now, even on Apple Silicon Macs. 
We will try to add Apple Silicon support in the future.
Is this the issue you are facing or there is something else?

**Comment by rrsadykov** [comment]
I close as no more activity in this issue.
