### ISSUE TITLE
Unable to run demo with Cplex

### ISSUE THREAD

**Issue by SmokeShine** [inria-UFF/VRPSolverEasy#17]
With default settings, the code runs without errors.
```
python HVRP_demo.py -i c50_13fsmd.txt -t 50                                 ─╯
['-i', 'c50_13fsmd.txt', '-t', '50']
************************************************************************************************
Search is finished, global bounds : [ 1491.85 , 1491.85 ], TIME = 0h0m1s87t = 187
************************************************************************************************
```
However, when trying to change the solver to CPLEX, it throws an error. 
> Error
```
python HVRP_demo.py -i c50_13fsmd.txt -t 50 -s CPLEX -p /Applications/CPLEX_Studio2211/cplex/bin/x86-64_osx/cplex
['-i', 'c50_13fsmd.txt', '-t', '50', '-s', 'CPLEX', '-p', '/Applications/CPLEX_Studio2211/cplex/bin/x86-64_osx/cplex']
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
VRPSolver v0.6.11, 2/12/2023, © Inria Bordeaux, France, vrpsolver.math.u-bordeaux.fr
      Corresponds to the solver by Pessoa, Sadykov, Uchoa and Vanderbeck (2020)
                 Paper: dx.doi.org/10.1007/s10107-020-01523-z
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   BaPCod v0.82.5, 24/09/2023, © Inria Bordeaux, France, bapcod.math.u-bordeaux.fr 
           THIS CODE IS PROVIDED AS IS, USE IT AT YOUR OWN RISK
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
BaPCod error : solver CPLEX is not found!
Please define CPLEX_ROOT environment variable before running cmake
```
> Environment variables
```
 which cplex                                                                 ─╯
/Applications/CPLEX_Studio2211/cplex/bin/x86-64_osx/cplex

```
```
echo $CPLEX_ROOT                                                            ─╯
/Applications/CPLEX_Studio2211
```
On running trace, the error originates from BAPCOD binary when calling `output = solve(input)` and it is difficult to debug this. What is the expected format of the string to be passed?

**Comment by najibprog** [comment]
Dear prateek,

Thank you for telling us about your issue. I've noticed that the binary you're using can't find Cplex, have you recompiled the Bapcod shared library with Cplex ? It's important to do this before to use Cplex in vrpsolvereasy. All these steps are detailed in the [documentation](https://vrpsolvereasy.readthedocs.io/en/latest/Installation/index.html#installation-of-academic-version).

Best regards,
Najib

**Comment by SmokeShine** [comment]
Hi,

Thanks for reverting. These are the steps that I followed:

Extracted rcsp.zip in the tools folder
1. wget -P Tools/https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz
3. wget -P Tools/ http://lemon.cs.elte.hu/pub/sources/lemon-1.3.1.tar.gz
4. bash Scripts/shell/install_bc_lemon_mac_m1.sh
5. bash Scripts/shell/install_bc_boost_mac_m1.sh
6. cd Tools & git clone https://github.com/Tencent/rapidjson/
7. cd ..
8. export CPLEX_ROOT=/Applications/CPLEX_Studio2211
9. mkdir build
10. cmake -DCMAKE_BUILD_TYPE=Release ..
11. make -j8 bapcod
12. cd build/Demos/VertexColoring <<<< Error. Folder does not exist
13. cd build/Demos/VehicleRoutingWithTimeWindows <<<< Error. Folder does not exist
14. cmake --build build --config Release --target bapcod-shared  <<< Error

```
warning: ignoring file '/Users/xxx/Downloads/bapcod-v0.82.5/Tools/rcsp/lib/librcspmacos.a[2](base_solver.cpp.o)': found architecture 'x86_64', required architecture 'arm64'

...
...
...

clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [Bapcod/libbapcod-shared.dylib] Error 1
make[2]: *** [Bapcod/CMakeFiles/bapcod-shared.dir/all] Error 2
make[1]: *** [Bapcod/CMakeFiles/bapcod-shared.dir/rule] Error 2
make: *** [bapcod-shared] Error 2
```

**Comment by rrsadykov** [comment]
@najibprog Do you have time to check whether these steps work for you ?

**Comment by rrsadykov** [comment]
The latest distribution of BaPCod is compatible with Apple Silicon processors. So, you need to use the ARM version of Cplex, and compile both Lemon and Boost normally:
```
bash Scripts/shell/install_bc_lemon.sh
bash Scripts/shell/install_bc_boost.sh
```
For demos, you need to add `Demo` at the end (sorry for that, we will update the instructions):
```
cd build/Demos/VertexColoringDemo
cd build/Demos/VehicleRoutingWithTimeWindowsDemo
```
@najibprog, building of VehicleRoutingWithTimeWindowsDemo is deactivated in the `Demos/CMakeLists.txt` file in the latest BaPCod distribution, one needs to activate it.
