### ISSUE TITLE
Issue: Arc Elimination Eliminates All Arcs at Root Node Even When the Optimality Gap is 1000000.

### ISSUE THREAD

**Issue by Zhengzhong-You** [inria-UFF/VRPSolverEasy#23]
[A-n60-k9.txt](https://github.com/inria-UFF/VRPSolverEasy/files/14817003/A-n60-k9.txt)

All CVRP instances seem to have the same issue. (I'm using cplex as the internal solver)

<it=419> <et=1.79> <Mt= 0.00> <Spt= 0.04> <nCl=  8> <DB=  443.0000> <Mlp=  443.0000> <PB=1000000> 
Reduced cost fixing for graph G_1...  TT = 0.001026, pt = 1e-05, dt = 0.000801, ct = 0, ndl = 0', bdl = 0', bdch = 0', odch = 0', lcp = 0'
took 0 sec., 0 buck. arcs remain (0% from prev., 0% from max.)
Run enumeration... took 0 sec. and succeeded! 
ColGenEvalAlg final dual bound: 443 (rounded: 443)
----- Terminating the node by MIP -----
************************************************************************************************
Search is finished, global bounds : [ 1e+06 , 1e+06 ], TIME = 0h0m1s94t = 194
************************************************************************************************
Statistics :
        best lower bound : 1000000.0 
        
        solution time : 1.941783757
        
        number of nodes : 1
        
        solution value : 0.0

        root lower bound : 1000000.0

        root root time : 1.941402197.
        
Status : 2.

Message : Better solution doesn't exist..

**Comment by rrsadykov** [comment]
We need to reproduce this issue. Could you attach here the JSON file for your instance together with the configuration file (if you use it). Also, what is yours operating system?

**Comment by Zhengzhong-You** [comment]
[A-n60-k9.json](https://github.com/inria-UFF/VRPSolverEasy/files/14825691/A-n60-k9.json)
[CVRP_cfg.json](https://github.com/inria-UFF/VRPSolverEasy/files/14825692/CVRP_cfg.json)
Sure, my operating system is Linux. And in CVRP.py, to let the model read configurations, I made the following changes.

  # set parameters
    model.set_parameters(time_limit=time_resolution,
                         solver_name=solver_name_input,
                         upper_bound=ub,
                         config_file=config_file)

**Comment by rrsadykov** [comment]
Dear @Zhengzhong-You, 
These are not the right JSON files, we need the JSON file produced by the `model.export()` command.

**Comment by rrsadykov** [comment]
Yes, this is the right file. I would also need `CVRP.cfg` file you use for parameterization.

**Comment by Zhengzhong-You** [comment]
> Yes, this is the right file. I would also need `CVRP.cfg` file you use for parameterization.

I cannot upload a file with the extension .cfg. So I changed the name to "CVRP_cfg.json", as uploaded above. You can also download it here (they are the same file).

[CVRP_cfg.json](https://github.com/inria-UFF/VRPSolverEasy/files/14873801/CVRP_cfg.json)

**Comment by rrsadykov** [comment]
Dear @Zhengzhong-You,

This issue comes from the configuration file. When using VRPSolver extension from BaPCod, one always needs to set these parameters:
```
MaxNbOfStagesInColGenProcedure = 3
colGenSubProbSolMode = 3
```
This is indicated in the BaPCod user guide (Section 6.4). 

In addition, to use simplified strong branching parameterisation (as in your config file), one needs to set
```
SimplifiedStrongBranchingParameterisation = true
```
This is also indicated in the BaPCod user guide (Section 3.6). 

Also, to run one-thread version (good for time comparison in papers), one should set
```
MipSolverMultiThread = 1
```
Please add these four parameter settings in your config file, and you should be fine. Please report here if this resolves your issue.

I agree that this is not well indicated in the VRPSolverEasy documentation, we will update it accordingly. Thank you for reporting this issue.

**Comment by Zhengzhong-You** [comment]
Dear Dr. @rrsadykov ,

Thank you for your detailed explanation and guidance on configuring the VRPSolver extension from BaPCod. I have added the parameters you suggested to my configuration file and these changes have resolved the issue. I appreciate your assistance and am grateful for your support in updating the documentation to make it clearer. Thank you once again!

Best regards,
Zhengzhong
