### ISSUE TITLE
MDVRP input file 

### ISSUE THREAD

**Issue by mventura00** [inria-UFF/VRPSolverEasy#7]
Hi !
As I have been working a lot today to try to get the 'MDVRP' python program to run, I did have some questions on the input file (I used the 'p01' provided on GitHub demos/data/MDVRP). Please see attached.
Do you have some sort of document that defines everything that goes into the 'input' file? That would be helpful for the user who is new.

[p01_multidepot.txt](https://github.com/inria-UFF/VRPSolverEasy/files/12176640/p01_multidepot.txt)

In row #1, it has: 2 4 50 4  
What does the 2 mean? I assume 4 means '4 depots'. the 50 means '50 cities'. what does the other 4 mean?

In row 2-5:   0 80
(this is repeated for all rows). What does the 0 and 80 represent? Is 80 the capacity for each of the depots? 

Starting on row #6, it has 1 (which is the first city). It has these values for row #6: 
1 37 52 0   7 1 4 1 2 4 8

I imagine, 37 and 52 are the latitude and longitude. What does the 0 mean? And, what then do the next 7 digits (7 1 4 1 2 4 8) represent? 

The last 4 rows are the attributes of the 4 depots:
51 20 20 0   0 0 0
52 30 40 0   0 0 0
53 50 30 0   0 0 0
54 60 50 0   0 0 0

So, in row #51, does the 20 20 , represent the latitude = 20 and longitude =20? What do the next 4 zeroes represent? Are they just placeholders?

**Comment by mventura00** [comment]
??

**Comment by rrsadykov** [comment]
I close this issue as a similar question is asked in issue #9.
