### ISSUE TITLE
MDVRP - original code runs but does not print out routes. Help!

### ISSUE THREAD

**Issue by mventura00** [inria-UFF/VRPSolverEasy#8]
Hello!
Here is the original code that software developers provided on your GitHub. See attached. I also provide one of the input files (provided on Github called 'p01'
[MDVRP_original.zip](https://github.com/inria-UFF/VRPSolverEasy/files/12234242/MDVRP_original.zip)
[p01_multidepot.zip](https://github.com/inria-UFF/VRPSolverEasy/files/12234245/p01_multidepot.zip)

(I had to zip the files bc it wouldnt let me attach it for some reason!!)

**If you run it, the output is:**
New model incumbent solution 576.865, TIME = 0h0m8s86t = 886
************************************************************************************************
Search is finished, global bounds : [ 576.865 , 576.865 ], TIME = 0h0m8s86t = 886
--

How do you get it to print the routes of the trucks? Any help would be greatly appreciated!! Thanks!

**Comment by mventura00** [comment]
I can meet someone (a developer) on Zoom if that is easier?

**Comment by mventura00** [comment]
Talked with another PhD student and figured it out! 
We had to add this part to the code: (under 'if model.solution.is_defined :' ) , BELOW.
The output tells you the route of which vehicle, but doesnt tell you form which 'depot' (since its a multi-depot) it leaves from! How do I do that? I print the OUTPUT at the very bottom! 


  print(f"""Statistics :
              best lower bound : { model.statistics.best_lb }
              solution time : {model.statistics.solution_time}
              number of nodes : {model.statistics.nb_branch_and_bound_nodes}
              solution value : {model.solution.value}
              root lower bound : {model.statistics.root_lb}
              root root time : {model.statistics.root_time}.
        """)
        print(f"Status : {model.status}.\n")
        print(f"Message : {model.message}.\n")  
        
        for route in model.solution.routes:            
            print(f"Vehicle Type id : {route.vehicle_type_id}.")
            print(f"Ids : {route.point_ids}.")
            print(f"Load : {route.cap_consumption}.\n")



**_OUTPUT:_**

Statistics :
              best lower bound : 673.478
              solution time : 15.5534867
              number of nodes : 1
              solution value : 673.478
              root lower bound : 673.478
              root root time : 15.5351252.

Status : 0.
[NEW multidepot.zip](https://github.com/inria-UFF/VRPSolverEasy/files/12234432/NEW.multidepot.zip)


Message : The solution found is optimal..

Vehicle Type id : 51.
Ids : [51, 46, 11, 51].
Load : [0.0, 25.0, 54.0, 54.0].

Vehicle Type id : 53.
Ids : [53, 34, 35, 19, 53].
Load : [0.0, 17.0, 23.0, 51.0, 51.0].

Vehicle Type id : 50.
Ids : [50, 12, 24, 50].
Load : [0.0, 23.0, 51.0, 51.0].

Vehicle Type id : 52.
Ids : [52, 49, 33, 29, 52].
Load : [0.0, 10.0, 36.0, 55.0, 55.0].

Vehicle Type id : 51.
Ids : [51, 23, 42, 6, 22, 51].
Load : [0.0, 10.0, 21.0, 40.0, 56.0, 56.0].

Vehicle Type id : 52.
Ids : [52, 48, 4, 37, 52].
Load : [0.0, 18.0, 39.0, 54.0, 54.0].

Vehicle Type id : 53.
Ids : [53, 20, 15, 1, 53].
Load : [0.0, 8.0, 23.0, 53.0, 53.0].

Vehicle Type id : 50.
Ids : [50, 41, 18, 39, 40, 50].
Load : [0.0, 13.0, 22.0, 29.0, 56.0, 56.0].

Vehicle Type id : 50.
Ids : [50, 3, 17, 50].
Load : [0.0, 9.0, 50.0, 50.0].

Vehicle Type id : 51.
Ids : [51, 47, 25, 7, 0, 51].
Load : [0.0, 17.0, 24.0, 47.0, 54.0, 54.0].

Vehicle Type id : 51.
Ids : [51, 45, 10, 31, 51].
Load : [0.0, 5.0, 24.0, 36.0, 36.0].

Vehicle Type id : 52.
Ids : [52, 8, 38, 32, 9, 52].
Load : [0.0, 11.0, 25.0, 48.0, 53.0, 53.0].

Vehicle Type id : 50.
Ids : [50, 43, 44, 14, 36, 16, 50].
Load : [0.0, 16.0, 26.0, 36.0, 45.0, 48.0, 48.0].

Vehicle Type id : 53.
Ids : [53, 2, 27, 30, 21, 28, 53].
Load : [0.0, 16.0, 30.0, 41.0, 49.0, 55.0, 55.0].

Vehicle Type id : 51.
Ids : [51, 13, 5, 26, 51].
Load : [0.0, 21.0, 36.0, 51.0, 51.0].

**Comment by rrsadykov** [comment]
Dear @mventura00,

Sorry for a long answer, there is now the vacation period in France. 

Your code is ok.

To know the depot for a route in the solution, you should look for the first point id. It corresponds to the depot from which vehicle starts from.

**Comment by mventura00** [comment]
Thank you very much! 

Question 1: where do we specify in this data input file, what the latitude and longitude of the depot is (to tell it where it is located)? I looked at the website you gave me (in the other issue which was SO helpful) but in the data representation/ definition, there doesnt seem to be a place where you specify location of the depot. 

I saw in this other site: https://github.com/inria-UFF/VRPSolverEasy/blob/master/docs/Demos/MDVRP.rst
**### It has this:**
nb_depots = 2
nb_customers = 3
vehicle_capacity = 60
cust_demands = [15,52,65]
cust_coordinates = [[55.21,44.36],[57.81,53.27]]
depot_coordinates = [[54.69,57.36],[54.31,65.23]]

So  do we put that directly in the MDVRP.py   and modify it for our problem then? 

Question 2: how do we know what to put for teh # of possible visit combinations? and the list of all possible visit combinations?

Question 3: for beginning of time window, does

**Comment by rrsadykov** [comment]
Dear Marta @mventura00,

In the description of the instance format, one can read: _In the case of the MDVRP, the lines go from 1 to n + t and the last t entries correspond to the t depots._ So, depot coordinates are given in the last lines. Visit combinations are ignored for the MDVRP, as well as time windows.

**Comment by mventura00** [comment]
> Dear @mventura00,
> 
> Sorry for a long answer, there is now the vacation period in France.
> 
> Your code is ok.
> 
> To know the depot for a route in the solution, you should look for the first point id. It corresponds to the depot from which vehicle starts from.

Thank you @rrsadykov !! Youre very nice and helpful.
