### ISSUE TITLE
MDVRP - how is the data (input file) represented?

### ISSUE THREAD

**Issue by mventura00** [inria-UFF/VRPSolverEasy#9]
I shorted the number of cities for one of the 'p01' input files , to make it easier to run the MDVRP program (keep it as simple as possible). 

How is the data represented exactly ? Here is input file
2 4 50 4
0 80
0 80
0 80
0 80
 1 37 52 0   7 1 4 1 2 4 8
 7 17 63 0  19 1 4 1 2 4 8
49 48 28 0  18 1 4 1 2 4 8
50 56 37 0  10 1 4 1 2 4 8
51 20 20 0   3 4 0
52 30 40 0   4 8 0
53 50 30 0   3 9 0
54 60 50 0   1 5 0

So, I can tell that: 51, 52, 53, and 54 , are the different vehicles and their capacity (20, 30, 40, 50) respectively. What does the number 3 4 0 mean (after vehicle 51)? 

And what are the 7 digits after city #1 mean? THe nubmers : 7 1 4 1 2 4 8 ?

And what is the first line mean?what is the 2? I know the 4 is 4 vehicle types? what is 50 ? what is the other 4?
what is the 0 80? 
[testing_mvrp.zip](https://github.com/inria-UFF/VRPSolverEasy/files/12234449/testing_mvrp.zip)

**Comment by rrsadykov** [comment]
Dear @mventura00,

The format of MDVRP instance files is described in https://github.com/fboliveira/MDVRP-Instances/blob/master/DESCRIPTION.md
